#!/usr/bin/env python3
"""
Download the Montserrat woff2 files and write assets/css/fonts.css.

Serving the font from our own domain removes a render-blocking request to
fonts.googleapis.com plus a DNS lookup and TLS handshake to fonts.gstatic.com —
on a phone that is usually a few hundred milliseconds before any text appears.

    python tools/fetch-fonts.py
"""

import os
import re
import sys
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(ROOT, 'assets', 'fonts')
CSS_OUT = os.path.join(ROOT, 'assets', 'css', 'fonts.css')

WEIGHTS = [400, 600, 700, 800]
API = 'https://fonts.googleapis.com/css2?family=Montserrat:wght@' + ';'.join(map(str, WEIGHTS)) + '&display=swap'
# a modern UA makes Google serve woff2 with unicode-range blocks
UA = ('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
      '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36')


def get(url, binary=False):
    req = urllib.request.Request(url, headers={'User-Agent': UA})
    data = urllib.request.urlopen(req, timeout=45).read()
    return data if binary else data.decode('utf-8')


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    css = get(API)

    blocks = re.findall(r'/\*\s*([\w-]+)\s*\*/\s*(@font-face\s*\{.*?\})', css, re.S)
    if not blocks:
        sys.exit('Google returned no @font-face blocks')

    out, seen = [], {}
    for subset, block in blocks:
        weight = re.search(r'font-weight:\s*(\d+)', block).group(1)
        url = re.search(r'url\((https://[^)]+\.woff2)\)', block).group(1)
        name = 'montserrat-%s-%s.woff2' % (weight, subset)
        path = os.path.join(OUT_DIR, name)
        if name not in seen:
            if not os.path.isfile(path):
                open(path, 'wb').write(get(url, binary=True))
            seen[name] = os.path.getsize(path)
        block = block.replace(url, '../fonts/' + name)
        out.append('/* %s */\n%s' % (subset, block.strip()))

    header = ('/* Montserrat, self-hosted.\n'
              '   Generated by tools/fetch-fonts.py — do not edit by hand. */\n\n')
    open(CSS_OUT, 'w', encoding='utf-8').write(header + '\n\n'.join(out) + '\n')

    total = sum(seen.values())
    print('font files : %d  (%.0f KB total, browser picks only what it needs)'
          % (len(seen), total / 1024))
    print('css        : %s' % os.path.relpath(CSS_OUT, ROOT).replace(os.sep, '/'))


if __name__ == '__main__':
    main()
